'use client'
import {useOnlineStatus} from '@/hooks/useOnlineStatus'
import {useWeather} from '@/hooks/useWeather'
import {useLocation} from '@/components/providers/LocationProvider'
import {DataProvenance} from '@/components/data/DataProvenance'
import {RiskBadge} from '@/components/risk/RiskBadge'
import {weatherReading} from '@/lib/weather'
import {heatIndexCelsius,heatIndexBand,formatHeatIndex} from '@/lib/thermal'
import type {WardRisk} from '@/lib/types'
import {formatTemp,formatDateTime} from '@/lib/utils'
export function WeatherKpis({risk,wbgt}:{risk?:WardRisk|null;wbgt?:number|null}){
 const {location,selectedDate}=useLocation(),query=useWeather(),{reading,label}=weatherReading(query.data),p=query.data?.provenance
 const online=useOnlineStatus()
 const hi=heatIndexCelsius(reading?.temperature,reading?.humidity),band=heatIndexBand(hi)
 const status=p?.status==='snapshot'?'snapshot':query.data&&(query.error||!online||p?.fromCache)?'cached':p?.status??(query.data?'live':'unavailable')
 const thermal=risk?.utci_max!=null?{label:'Thermal stress · UTCI',value:formatTemp(risk.utci_max)}:hi!==null?{label:'Thermal stress · Heat Index',value:formatHeatIndex(hi)}:{label:'Thermal stress · apparent',value:reading?.apparent==null?'Unavailable':formatTemp(reading.apparent)}
 const primary=[{label:'Air temperature',value:reading?.temperature==null?'Unavailable':formatTemp(reading.temperature)},{label:'Humidity',value:reading?.humidity==null?'Unavailable':`${reading.humidity.toFixed(0)}%`},thermal]
 const temperatures=query.data?.hourly.map(h=>h.temperature).filter((v):v is number=>v!==null)??[]
 return <section aria-label="Heat and weather conditions" className="space-y-2"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4" data-testid="kpi-grid">{primary.map(cell=><div key={cell.label} className="min-w-0 rounded-lg border bg-card p-3"><h2 className="text-xs font-medium tapas-subtext">{cell.label}</h2><p className={`mt-2 break-words text-2xl font-semibold tabular-nums ${query.isLoading?'animate-pulse':''}`}>{query.isLoading?'Loading…':cell.value}</p><p className="mt-1 text-[11px] tapas-subtext">{status.toUpperCase()} · {label}</p></div>)}<div className="min-w-0 rounded-lg border bg-card p-3"><h2 className="text-xs font-medium tapas-subtext">Heat risk level</h2><div className="mt-3">{risk?.risk_level ? <RiskBadge level={risk.risk_level}/>:<p className="text-lg font-semibold" style={{color:band?.color}}>{band?.label??'Unavailable'}</p>}</div><p className="mt-1 text-[11px] tapas-subtext">{risk?.risk_level?'Supplied local risk':band?'NOAA Heat Index category · not an official alert':'No valid HI category; absence does not mean safe.'}</p></div></div><div className="flex flex-wrap gap-x-6 gap-y-1 text-xs tapas-subtext"><span>Apparent temperature: {reading?.apparent==null?'Unavailable':formatTemp(reading.apparent)}</span><span>WBGT: {wbgt==null?'Unavailable':formatTemp(wbgt)}</span><span>Wind: {reading?.wind==null?'Unavailable':`${reading.wind.toFixed(1)} m/s`}</span><span>Forecast peak: {temperatures.length&&p?.status!=='snapshot'?formatTemp(Math.max(...temperatures)):'Unavailable'}</span></div><p className="text-xs tapas-subtext">{location?.name??'India overview · select a weather point or search for local KPIs'} · Selected {selectedDate} · Asia/Kolkata{reading?` · Valid ${formatDateTime(reading.time)}`:''}. Model conditions, not station observations.</p><DataProvenance status={status} source={p?.source} timestamp={reading?.time??p?.originalAt} note={p?.note}/>{query.error&&!query.data?<p role="status" className="text-xs">Live, cached and recorded weather unavailable for this location. <button className="min-h-11 underline" onClick={()=>void query.refetch()}>Retry weather</button></p>:null}<p className="text-[11px] tapas-subtext"><a className="underline" href="https://open-meteo.com/en/docs" target="_blank" rel="noopener noreferrer">Weather by Open-Meteo · CC BY 4.0</a> · <a className="underline" href="https://www.weather.gov/safety/heat-index" target="_blank" rel="noopener noreferrer">NOAA Heat Index</a> applies to shade/light wind. UTCI and WBGT require validated additional inputs.</p></section>
}
