const fs=require('fs');
async function get(url){const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`${r.status} ${url}`);return {payload:await r.json(),url,capturedAt:new Date().toISOString()}}
function insideRing(lon,lat,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if((yi>lat)!=(yj>lat)&&lon<(xj-xi)*(lat-yi)/(yj-yi)+xi)inside=!inside}return inside}
function onLand(lon,lat,geometry){const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;return polygons.some(p=>insideRing(lon,lat,p[0])&&!p.slice(1).some(r=>insideRing(lon,lat,r)))}
(async()=>{
 const source='https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson';const borders=await get(source);const india=borders.payload.features.find(f=>f.properties.ADM0_A3==='IND');if(!india)throw Error('India land mask missing');
 fs.writeFileSync('src/data/india-land-mask.json',JSON.stringify({source,capturedAt:borders.capturedAt,note:'Natural Earth coarse sampling mask; not authoritative administrative boundaries.',geometry:india.geometry}));
 let grid=[];for(const step of [1.5,1.75,2,2.25,2.5]){const points=[];for(let lat=7;lat<36;lat+=step)for(let lon=68.5;lon<98;lon+=step)if(onLand(lon,lat,india.geometry))points.push({latitude:Number(lat.toFixed(4)),longitude:Number(lon.toFixed(4)),name:`Grid ${lat.toFixed(2)}, ${lon.toFixed(2)}`});if(points.length>=60&&points.length<=85){grid=points;break}}if(!grid.length)throw Error('Grid target not met');
 fs.writeFileSync('src/data/national-grid.json',JSON.stringify(grid));console.log(JSON.stringify({maskPoints:india.geometry.coordinates.length,gridPoints:grid.length}));
 const names=['Hyderabad','Mumbai','Karimnagar','Delhi','Chennai','Kolkata','Bengaluru','Ahmedabad','Jaipur','Lucknow','Patna','Bhopal','Nagpur','Pune','Surat','Kanpur','Varanasi','Agra','Kochi','Thiruvananthapuram','Bhubaneswar','Raipur','Ranchi','Guwahati','Shillong','Imphal','Srinagar','Shimla','Chandigarh','Visakhapatnam'];
 const cities=[];for(const name of names){const url='https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name,count:'10',language:'en',format:'json',countryCode:'IN'});const result=await get(url);const p=result.payload.results?.find(p=>p.country_code==='IN');if(!p)throw Error('No genuine geocode for '+name);cities.push({name:p.name,latitude:p.latitude,longitude:p.longitude,state:p.admin1,timezone:p.timezone,geocode:result});}
 const requests=[...grid,...cities.map(({name,latitude,longitude})=>({name,latitude,longitude}))];const recordings=[];
 for(let i=0;i<requests.length;i+=50){const group=requests.slice(i,i+50);const url='https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:group.map(p=>p.latitude).join(','),longitude:group.map(p=>p.longitude).join(','),current:'temperature_2m,relative_humidity_2m,wind_speed_10m,apparent_temperature,cloud_cover',hourly:'temperature_2m,relative_humidity_2m,wind_speed_10m,apparent_temperature,shortwave_radiation,direct_radiation',forecast_days:'5',timezone:'Asia/Kolkata',timeformat:'unixtime',wind_speed_unit:'ms'});const response=await get(url);if(!Array.isArray(response.payload)||response.payload.length!==group.length)throw Error('Batch mismatch');recordings.push({requests:group,source:response.url,capturedAt:response.capturedAt,data:response.payload});console.log('Captured '+group.length+' genuine weather results');}
 fs.writeFileSync('src/data/weather-snapshot.json',JSON.stringify({provider:'Open-Meteo best-match weather models',note:'Recorded genuine response; replayed with original coordinates and valid time when the live provider is unavailable.',cities,recordings}));
 require('./derive-weather.cjs');
 console.log(JSON.stringify({national:grid.length,cities:cities.length,recorded:requests.length,capturedAt:recordings[0].capturedAt}));
})().catch(e=>{console.error(e);process.exitCode=1});
